services:
  - type: web
    name: astrograph
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: GRAPH_PATH
        value: knowledge_graph.graphml
